language: python
python:
- '3.6'
cache: pip
install:
- python --version
- pip install scipy
- pip install --upgrade pytest
- pip install --upgrade lygadgets
- pip install --upgrade lytest
script:
- DOCKER=1 pytest tests
